/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package funger;

import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.*;

/**
 *
 * @author sergi
 */
public class FormInventario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormInventario.class.getName());

    private GestoreGioco gestoreGioco;
    private DefaultListModel<String> oggetti = new DefaultListModel();
    private JList listaOggetti;
    private JPanel panelParty = new JPanel();
    /**
     * Creates new form FormInventario
     */
    public FormInventario(GestoreGioco gestoreGioco) {
        initComponents();
        this.gestoreGioco = gestoreGioco;
        PanelSfondo sfondo = new PanelSfondo("img/background.png");
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setSize(new Dimension(900, 500));
        this.setContentPane(sfondo);
        this.setLayout(new GridLayout(1, 2));
        
        creaPanelOggetti();
        this.add(panelParty);
        
        creaPanelParty();
    }

    public void creaPanelOggetti(){
        listaOggetti = new JList(oggetti);
        listaOggetti.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
            int index = listaOggetti.getSelectedIndex();

            if (index != -1 && !gestoreGioco.getOggetti().isEmpty()) {

                Oggetto oggettoSelezionato = gestoreGioco.getOggetti().get(index);
                DialogUtilizzoOggetto dialog = new DialogUtilizzoOggetto(oggettoSelezionato, gestoreGioco);
            }
        }
        });
        
        JScrollPane scrollPane = new JScrollPane(listaOggetti); 

        aggiornaOggetti();

        this.add(scrollPane);
    }
    
    public void aggiornaOggetti(){       
        oggetti.clear();
        for(Oggetto o : gestoreGioco.getOggetti()){
            oggetti.addElement(o.getNome());
        }
    }
    
    public void creaPanelParty(){
        panelParty.removeAll();
        panelParty.setLayout(new GridLayout(gestoreGioco.getGrandezzaParty(), 1));
        
        for(Giocabile g : gestoreGioco.getParty()){
            JPanel panelPersonaggio = new JPanel();
            if(g instanceof Giocatore)
                panelPersonaggio.setLayout(new GridLayout(1, 4));
            else
                panelPersonaggio.setLayout(new GridLayout(1, 2));
            
            panelPersonaggio.add(new JLabelPersonalizzato(g.getSprite()));
            
            if(g instanceof Giocatore){
                if(((Giocatore) g).getOggettoOffensivo() != null)
                    panelPersonaggio.add(new JLabelPersonalizzato(((Giocatore) g).getOggettoOffensivo().getSprite()));
                else
                    panelPersonaggio.add(new JLabelPersonalizzato("Niente"));
                
                if(((Giocatore) g).getOggettoDifensivo() != null)
                    panelPersonaggio.add(new JLabelPersonalizzato(((Giocatore) g).getOggettoDifensivo().getSprite()));
                else
                    panelPersonaggio.add(new JLabelPersonalizzato("Niente"));
            }
            
            JPanel panelBarre = new JPanel();
            if(g instanceof Giocatore){
                panelBarre.setLayout(new GridLayout(3, 1));
                JProgressBar barraVita = new JProgressBar(0, g.getVitaMax());
                barraVita.setValue(g.getVita());
                barraVita.setStringPainted(true);
                panelBarre.add(barraVita);
                
                JProgressBar barraFame = new JProgressBar(0, 100);
                barraFame.setValue(((Giocatore)g).getFame());
                barraFame.setStringPainted(true);
                panelBarre.add(barraFame);
                
                JProgressBar barraMente = new JProgressBar(0, 100);
                barraMente.setValue(((Giocatore)g).getMente());
                barraMente.setStringPainted(true);
                panelBarre.add(barraMente);
            }
            else{
                panelBarre.setLayout(new GridLayout(1, 1));
                JProgressBar barraVita = new JProgressBar(0, g.getVitaMax());
                barraVita.setValue(g.getVita());
                barraVita.setStringPainted(true);
                panelBarre.add(barraVita);
            }
            
            panelPersonaggio.add(panelBarre);
            
            panelParty.add(panelPersonaggio); 
        }
        panelParty.revalidate();
        panelParty.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
