/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package funger;

import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author sergi
 */
public class FormMappa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMappa.class.getName());

    private GestoreGioco gestoreGioco;
    private Mappa mappaScoperta;
    /**
     * Creates new form FormMappa
     */
    public FormMappa(GestoreGioco gestoreGioco) {
        initComponents();
        this.gestoreGioco = gestoreGioco;
        this.setSize(new Dimension(500, 500));
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        mappaScoperta = new Mappa(gestoreGioco.getGrandezzaMappa());
    }
    
    public void aggiornaMappaScoperta(){
        int[] posizione = gestoreGioco.getPosizione();
        TipoCella[] tipi = gestoreGioco.getCelleAdiacenti();
        mappaScoperta.aggiungiCella(new Cella(tipi[0]), posizione[0]+1, posizione[1]);
        mappaScoperta.aggiungiCella(new Cella(tipi[1]), posizione[0], posizione[1]+1);
        mappaScoperta.aggiungiCella(new Cella(tipi[2]), posizione[0], posizione[1]);
        mappaScoperta.aggiungiCella(new Cella(tipi[3]), posizione[0], posizione[1]-1);
        mappaScoperta.aggiungiCella(new Cella(tipi[4]), posizione[0]-1, posizione[1]);       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
