/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package funger;

import java.awt.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import javax.swing.*;

/**
 *
 * @author cucchiarini.cesare
 */
public class FormScelta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormScelta.class.getName());

    
    private GestoreGioco gestoreGioco;
    private HashMap<Giocatore, String> mappaPersonaggi = new HashMap<>();
    /**
     * Creates new form FormScelta
     */
    public FormScelta() {
        initComponents();
        gestoreGioco = new GestoreGioco();
        GestoreFile.setGestoreGioco(gestoreGioco);
        this.setLayout(new BorderLayout());
        
        generaScelta();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
    }
    
    public void generaScelta(){
        mappaPersonaggi = GestoreFile.leggiInizio();
        JPanel panelScelta = new JPanel();
        panelScelta.setBorder(BorderFactory.createEmptyBorder(10,30,10,30));
        panelScelta.setLayout(new GridLayout(1, 4, 10, 0));
        
        for(Map.Entry<Giocatore, String> entry : mappaPersonaggi.entrySet()){
            JPanel p = new JPanel();
            p.setBorder(BorderFactory.createLineBorder(Color.black));
            p.setLayout(new BorderLayout());
            
            p.add(new JLabel(entry.getKey().getSprite()), BorderLayout.CENTER);
            
            JButton bottoneScelta = new JButton("Scegli");         
            bottoneScelta.setAlignmentX(CENTER_ALIGNMENT);
            bottoneScelta.setFont(bottoneScelta.getFont().deriveFont(20.0f));
            
            bottoneScelta.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e){
                    gestoreGioco.inizializza(entry.getKey());
                }
            });
            
            JButton bottoneInfo = new JButton("Info");
            bottoneInfo.setAlignmentX(CENTER_ALIGNMENT);
            bottoneInfo.setFont(bottoneScelta.getFont());
            
            bottoneInfo.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e){
                    JOptionPane.showMessageDialog(null, entry.getValue());
                }
            });
             
            JPanel panelBottoni = new JPanel();
            panelBottoni.setLayout(new BoxLayout(panelBottoni, BoxLayout.Y_AXIS));
            panelBottoni.add(bottoneScelta);
            panelBottoni.add(bottoneInfo);
            panelBottoni.setBorder(BorderFactory.createEmptyBorder(0, 0, 20, 0));
            
            p.add(panelBottoni, BorderLayout.SOUTH);         
            panelScelta.add(p);
        }
        panelScelta.setBackground(Color.red);
        
        this.add(panelScelta, BorderLayout.CENTER);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormScelta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
