/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package funger;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.util.Map;
import javax.swing.*;

/**
 *
 * @author sergi
 */
public class FormMappa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMappa.class.getName());

    private GestoreGioco gestoreGioco;
    private Mappa mappa;
    private JPanel[][] grigliaPanel;
    private Map<TipoCella, Color> mappaColori = Map.of(
            TipoCella.MURO, Color.BLACK,
            TipoCella.INIZIO, Color.GREEN,
            TipoCella.FINE, Color.BLUE,
            TipoCella.PIENO, Color.YELLOW,
            TipoCella.VUOTO, Color.LIGHT_GRAY
        );
    /**
     * Creates new form FormMappa
     */
    public FormMappa(GestoreGioco gestoreGioco) {
        initComponents();
        this.gestoreGioco = gestoreGioco;
        this.setSize(new Dimension(500, 500));
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        mappa = gestoreGioco.getMappa();
        creaGrigliaMappa();
        
        aggiungiKeyListener();
    }
    
    public void aggiungiKeyListener(){
        InputMap im = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = this.getRootPane().getActionMap();

        int[] keyCodes = {38, 40, 37, 39}; // Up, Down, Left, Right
        String[] names = {"moveUp", "moveDown", "moveLeft", "moveRight"};

        for (int i = 0; i < keyCodes.length; i++) {
            final int keyCode = keyCodes[i];

            im.put(KeyStroke.getKeyStroke(keyCode, 0), names[i]);

            am.put(names[i], new AbstractAction() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int[] mov = GestoreInput.getMappaMovimenti().get(keyCode);
                    if (mov != null) {
                        gestoreGioco.muovi(mov[0], mov[1]);
                    }
                }
            });
        }
    }
    
    public void mostraMappa(){
        aggiornaGrigliaMappa();
        this.setVisible(true);
    }
    
    public void creaGrigliaMappa(){
        int righe = mappa.getRighe() + 2;
        grigliaPanel = new JPanel[righe][righe];
        this.setLayout(new GridLayout(righe, righe));

        for(int i = 0; i < righe; i++){
            for(int j = 0; j < righe; j++){
                JPanel cella = new JPanel();
                cella.setBorder(BorderFactory.createLineBorder(Color.black));
                cella.setBackground(Color.DARK_GRAY);
                grigliaPanel[i][j] = cella;
                this.add(cella);
            }
        }
    }
    
    public void aggiornaGrigliaMappa(){
        int righe = mappa.getRighe();
        
        for(int x = 0; x < righe+1; x++){
            for(int y = 0; y < righe+1; y++){
                if(!mappa.cellaInizializzata(x, y))
                    continue;
                if(mappa.getStatoCella(x, y) != Cella.NON_VISITATA){
                    grigliaPanel[x+1][y+1].setBackground(mappaColori.get(mappa.getTipoCella(x, y)));
                    grigliaPanel[x][y+1].setBackground(mappaColori.get(mappa.getTipoCella(x-1, y)));
                    grigliaPanel[x+2][y+1].setBackground(mappaColori.get(mappa.getTipoCella(x+1, y)));
                    grigliaPanel[x+1][y].setBackground(mappaColori.get(mappa.getTipoCella(x, y-1)));
                    grigliaPanel[x+1][y+2].setBackground(mappaColori.get(mappa.getTipoCella(x, y+1)));
                }
            }
        }
        
        grigliaPanel[gestoreGioco.getX()+1][gestoreGioco.getY()+1].setBackground(Color.red);
        
        this.revalidate();
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
