/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package funger;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author cucchiarini.cesare
 */
public class FormGioco extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormGioco.class.getName());
    
    private GestoreGioco gestoreGioco;
    private JPanel panelGioco;
    private JPanel panelLaterale;
    /**
     * Creates new form FormGioco
     */
    public FormGioco(GestoreGioco gestoreGioco) {
        initComponents();
        this.gestoreGioco = gestoreGioco;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLayout(new BorderLayout());
        
        creaPanelGioco();
        creaPanelLaterale();
        
        this.getContentPane().setBackground(Color.red);
        this.setVisible(true);
    }
    
    /**
     * crea e aggiunge al frame il panel che mostra cosa sta accandendo nella stanza
     */
    public void creaPanelGioco(){
        panelGioco = new JPanel();
        panelGioco.setLayout(new GridLayout(1, 2));
        
        aggiornaPanelGioco();
        
        panelGioco.setOpaque(false);
        panelGioco.setBorder(BorderFactory.createLineBorder(Color.black));
        this.add(panelGioco, BorderLayout.CENTER);
    }
    
    /**
     * aggiorna le immagini nel panel del gioco
     */
    public void aggiornaPanelGioco(){
        panelGioco.removeAll();
        aggiornaPanelParty();
        aggiornaPanelCreabile();
    }
    
    /**
     * aggiorna le immagini nel panel del party
     */
    public void aggiornaPanelParty(){
        JPanel panelParty = new JPanel();
        panelParty.setOpaque(false);
        panelParty.setLayout(new GridLayout(1, gestoreGioco.getGrandezzaParty()));
        
        for(Giocabile g : gestoreGioco.getParty()){
            panelParty.add(new JLabel("party"));
        }
        
        panelGioco.add(panelParty);
    }
    
    /**
     * aggiorna le pagine nel panel del creabile
     */
    public void aggiornaPanelCreabile(){
        JPanel panelCreabile = new JPanel();
        panelCreabile.setOpaque(false);
        panelCreabile.setLayout(new BoxLayout(panelCreabile, BoxLayout.X_AXIS));
        
        panelCreabile.add(new JLabel("creabile"));
        
        panelGioco.add(panelCreabile);
    }
    
    /**
     * crea il panel laterale che mostra vari bottoni e log
     */
    public void creaPanelLaterale(){
        panelLaterale = new JPanel();
        panelLaterale.setOpaque(false);
        panelLaterale.setLayout(new GridLayout(2, 1));
        
        panelLaterale.removeAll();
        creaTextArea();
        creaPanelBottoni();
        
        panelLaterale.setBorder(BorderFactory.createLineBorder(Color.black));
        panelLaterale.setPreferredSize(new Dimension(300, 0));
        this.add(panelLaterale, BorderLayout.EAST);
    }
    
    /**
     * crea la textArea che funziona da logger e la passa alla classe Logger
     */
    public void creaTextArea(){
        JTextArea textArea = new JTextArea();
        textArea.append("Log");
        panelLaterale.add(textArea);
        Logger.assegnaTextArea(textArea);
    }
    
    /**
     * crea il panel contenente i bottoni di inventario, mappa e informazioni
     */
    public void creaPanelBottoni(){
        JPanel panelBottoni = new JPanel();
        panelBottoni.setOpaque(false);
        panelBottoni.setLayout(new BoxLayout(panelBottoni, BoxLayout.Y_AXIS));
        
        JButton bottoneMappa = new JButton("Mappa");
        bottoneMappa.setAlignmentX(CENTER_ALIGNMENT);
        panelBottoni.add(bottoneMappa);
        
        JButton bottoneInventario = new JButton("Inventario");
        bottoneInventario.setAlignmentX(CENTER_ALIGNMENT);
        panelBottoni.add(bottoneInventario);
        
        JButton bottoneInfo = new JButton("?");
        bottoneInfo.setAlignmentX(CENTER_ALIGNMENT);
        panelBottoni.add(bottoneInfo);
        
        panelBottoni.setBorder(BorderFactory.createLineBorder(Color.black));
        panelLaterale.add(panelBottoni, BorderLayout.EAST);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
