---
config:
  layout: elk
---
classDiagram
direction TB
    class Giocatore {
	    -fame : int
	    -mente : int
        +Giocatore(nome : String, path : String)
	    +attacca() int
	    +utilizzaAbilita()*
	    +utilizzaOggetto(ogg : Oggetto)
	    +muovi()
        +controllaMorte() boolean
	    +perdiMente(perdita : int)
	    +guadagnaMente(guadagno : int)
        +perdiFame(perdita : int)
        +guadagnaFame(guadagno : int)
	    +setOggetto(oggetto : OggettoEquipaggiabile)
	    +getOggettoDifensivo() OggettoEquipaggiabile
        +getOggettoOffensivo() OggettoEquipaggiabile
        +consumaOggetto(oggetto : OggettoConsumabile)
    }

    class Party {
	    +aggiungiMembro(giocabile : Giocabile)
	    +rimuoviMembro(giocabile : Giocabile)
	    +getParty() ArrayList~Giocabile~
        +getGiocatori() ArrayList~Giocatore~
	    +getOggettiConsumabili() ArrayList~OggettoConsumabile~
	    +getOggettiEquipaggiabili() ArrayList~OggettoEquipaggiabile~
	    +cambiaOggetto(giocatore : Giocatore, oggetto : OggettoEquipaggiabile)
        +usaOggetto(giocatore : Giocatore, oggetto : OggettoConsumabile)
        +aggiungiOggetto(oggetto : OggettoConsumabile)
        +aggiungiOggetto(oggetto : OggettoEquipaggiabile)
    }

    class InventarioEquipaggiabili {
        +aggiungiOggetto(oggetto : OggettoEquipaggiabile)
	    +togliOggetto(oggetto : OggettoEquipaggiabile)
	    +getOggetti() ArrayList~OggettoEquipaggiabile~
    }

    class InventarioConsumabili {
        +aggiungiOggetto(oggetto : OggettoConsumabile)
	    +togliOggetto(oggetto : OggettoConsumabile)
	    +getOggetti() ArrayList~OggettoConsumabile~
    }

    class Mercenario {
	    +utilizzaAbilita()
    }

    class Cavaliere {
	    +utilizzaAbilita()
    }

    class Necromante {
	    +utilizzaAbilita()
    }

    class Vichingo {
	    +utilizzaAbilita()
    }

    class OggettoEquipaggiabile {
        -statPrincipale : int
        -agilita : int
        -tipo : TipoOggettoEquipaggiabile
        -nome : String
	    -sprite : ImageIcon
	    +getNome() String
	    +getSprite() ImageIcon
        +OggettoEquipaggiabile(nome : String, path : String, statprincipale : int, agilita : int, tipo :TipoOgettoEquipaggiabile)
        +getStatPrincipale() int 
        +getAgilita() int 
        +getTipo() TipoOggettoEquipaggiabile
    }

    class OggettoConsumabile {
        -statPrincipale : int 
        -tipo : TipoOggettoConsumabile
        -nome : String
	    -sprite : ImageIcon
	    +getNome() String
	    +getSprite() ImageIcon
        +OggettoConsumabile(nome : String, path : String, statprincipale : int, tipo : TipoOggettoConsumabile)
        +getStatPrincipale() int 
        +getTipo() TipoOggettoConsumabile
    }

    class TipoOggettoEquipaggiabile {
	    DIFENSIVO
	    OFFENSIVO
    }

    class TipoOggettoConsumabile {
	    COMMESTIBILE
	    CURATIVO
	    MENTALE
    }

    class Nemico {
    }

    class GestoreGioco {
	    -posizione : int[]
        -tipoCella : TipoCella
	    -mappaCreabili : HashMap~Integer, Consumer~Creabile~~
	    +GestoreGioco(leader : Giocatore,logger : Logger, mappa : Mappa)
	    +muovi(movX : int, movY : int)
        +interazioneCreabile()
	    +iniziaCombattimento()
	    +apriInventario()
	    +trovaOggetto()
	    +trovaAlleato()
	    +generaCreabile(id : int) Creabile
        +finePartita()

    }

    class Mappa {
        -righe : int 
        -numCella : int
        +Mappa(righe : int)
        +getGriglia(bordo : boolean) Cella[][]
        +aggiungiCella(cella : Cella)
	    +getInfosCella(x : int, y : int) int[]
        +setStatoCella(stato : int, x : int, y : int)
    }

    class Cella {
      +VISITATA : int
      +NON_VISITATA : int
      +COMPLETATA : int
	    -tipo : int
	    -idCreabile : int
      -stato : int
	    +getInfos() int[]
      +setStato(stato : int)
    }

    class GestoreInput {
    }

    class GestoreCombattimento {
	    +iniziaCombattimento(party : Party, nemico : Nemico)
        +calcolaAttacco() int
    }

    class TipoCella {
        VUOTO
	    MURO
	    NEMICO
	    OGGETTO
	    ALLEATO
        FINE
    }

    class GeneratoreMappa {
	    +generaMappa()$
    }

    class Creabile {
    }

    class Maneba {
        +attacca() int
    }

    class Guardia {
        +attacca() int
    }

    class Trotur {
        +attacca() int
    }

    class Logger{
        -textArea : JTextArea
        +Logger(textArea : JTextArea)
        +scriviMesaggio(msg : String)
    }

    class Giocabile{
        <<abstract>>
        -agilita : int
        -vita : int 
        -danno : int
        -sprite : ImageIcon
        -nome : String
        +Giocabile(nome : String, path : String)
        +attacca() int*
        +schiva() boolean
        +getDanno() int
        +getAgilita() int
        +getVita() int 
        +getSprite() ImageIcon
        +guadagnaVita(guadagno : int)
        +perdiVita(perdita : int)
        +controllaMorte() boolean
        +consumaOggetto(oggetto : OggettoConsumabile)
    }

	<<abstract>> Giocatore
	<<enum>> TipoOggettoEquipaggiabile
    <<enum>> TipoOggettoConsumabile
	<<abstract>> Nemico
	<<enum>> TipoCella
	<<interface>> Creabile

    Giocatore <|-- Mercenario
    Giocatore <|-- Cavaliere
    Giocatore <|-- Necromante
    Giocatore <|-- Vichingo
    Giocatore --|> Giocabile
    Creabile <|-- OggettoEquipaggiabile
    Creabile <|-- OggettoConsumabile
    Party "1" --> "1" InventarioConsumabili : -consumabili
    Party "1" --> "1" InventarioEquipaggiabili : -equipaggiabili
    InventarioConsumabili "1" --> "n" OggettoConsumabile : -consumabili
    InventarioEquipaggiabili "1" --> "n" OggettoEquipaggiabile : -equipaggiabili
    GestoreGioco "1" --> "1" Party : -party
    Party "1" --> "1...4" Giocabile : -personaggi
    GestoreInput "1" --> "1" Party : -party
    GestoreInput "1" --> "1" GestoreGioco : -gestoreGioco
    GestoreInput "1" --> "1" GestoreCombattimento : -gestoreCombattimento
    GestoreCombattimento "1" <--> "1" GestoreGioco : -gestoreCombattimento
    GestoreGioco "1" --> "1" Mappa : -mappa
    Giocatore "1" --> "1" OggettoEquipaggiabile : -oggettoDifensivo
    Giocatore "1" --> "1" OggettoEquipaggiabile : -oggettoOffensivo
    GeneratoreMappa "1" ..> "1" Mappa
    Mappa "1" *-- "n" Cella : -celle
    Nemico ..|> Creabile
    Maneba --|> Nemico
    Guardia --|> Nemico
    Trotur --|> Nemico
    GestoreGioco "1" --> "1" Creabile : -creabileCella 
    GestoreGioco "1" --> "1" Logger : -logger
    Nemico --|> Giocabile
    Giocabile <--> GestoreGioco